In [1]:
import pandas as pd
import numpy as np

In [2]:
# Apple Data
ios = pd.read_csv("AppleStore.csv")
ios.head()

,id,track_name,size_bytes,currency,price,rating_count_tot,rating_count_ver,user_rating,user_rating_ver,ver,cont_rating,prime_genre,sup_devices.num,ipadSc_urls.num,lang.num,vpp_lic
0,284882215,Facebook,389879808,USD,0.0,2974676,212,3.5,3.5,95.0,4+,Social Networking,37,1,29,1
1,389801252,Instagram,113954816,USD,0.0,2161558,1289,4.5,4.0,10.23,12+,Photo & Video,37,0,29,1
2,529479190,Clash of Clans,116476928,USD,0.0,2130805,579,4.5,4.5,9.24.12,9+,Games,38,5,18,1
3,420009108,Temple Run,65921024,USD,0.0,1724546,3842,4.5,4.0,1.6.2,9+,Games,40,5,1,1
4,284035177,Pandora - Music & Radio,130242560,USD,0.0,1126879,3594,4.0,4.5,8.4.1,12+,Music,37,4,1,1

In [3]:
# Google Play Store 
android = pd.read_csv("googleplaystore.csv")
android.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [4]:
def explore_data(df):
    print("Number of Rows: ",df.shape[0])
    print("Number of Cols: ",df.shape[1])
    return ''

In [5]:
print(explore_data(ios))
ios.head()

Number of Rows:  7197
Number of Cols:  16

,id,track_name,size_bytes,currency,price,rating_count_tot,rating_count_ver,user_rating,user_rating_ver,ver,cont_rating,prime_genre,sup_devices.num,ipadSc_urls.num,lang.num,vpp_lic
0,284882215,Facebook,389879808,USD,0.0,2974676,212,3.5,3.5,95.0,4+,Social Networking,37,1,29,1
1,389801252,Instagram,113954816,USD,0.0,2161558,1289,4.5,4.0,10.23,12+,Photo & Video,37,0,29,1
2,529479190,Clash of Clans,116476928,USD,0.0,2130805,579,4.5,4.5,9.24.12,9+,Games,38,5,18,1
3,420009108,Temple Run,65921024,USD,0.0,1724546,3842,4.5,4.0,1.6.2,9+,Games,40,5,1,1
4,284035177,Pandora - Music & Radio,130242560,USD,0.0,1126879,3594,4.0,4.5,8.4.1,12+,Music,37,4,1,1

In [6]:
print(explore_data(android))
android.head()

Number of Rows:  10841
Number of Cols:  13

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

### Delete Wrong Data

<p>The row 10472 corresponds to the app Life Made WI-Fi Touchscreen Photo Frame, and we can see that the rating is 19. This is clearly off because the maximum rating for a Google Play app is 5. As a consequence, we'll delete this row.</p>

In [7]:
android.iloc[np.where(android['Rating'] > 5)]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [8]:
android.shape

(10841, 13)

In [9]:
android.drop(10472,axis=0,inplace=True)

In [10]:
android.shape

(10840, 13)

## Remove Duplicate Entries

In [11]:
android[android.duplicated(['App'])]# List out all duplicate entries

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
229,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,"5,000,000+",Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up
236,Box,BUSINESS,4.2,159872,Varies with device,"10,000,000+",Free,0,Everyone,Business,"July 31, 2018",Varies with device,Varies with device
239,Google My Business,BUSINESS,4.4,70991,Varies with device,"5,000,000+",Free,0,Everyone,Business,"July 24, 2018",2.19.0.204537701,4.4 and up
256,ZOOM Cloud Meetings,BUSINESS,4.4,31614,37M,"10,000,000+",Free,0,Everyone,Business,"July 20, 2018",4.1.28165.0716,4.0 and up
261,join.me - Simple Meetings,BUSINESS,4.0,6989,Varies with device,"1,000,000+",Free,0,Everyone,Business,"July 16, 2018",4.3.0.508,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10715,FarmersOnly Dating,DATING,3.0,1145,1.4M,"100,000+",Free,0,Mature 17+,Dating,"February 25, 2016",2.2,4.0 and up
10720,Firefox Focus: The privacy browser,COMMUNICATION,4.4,36981,4.0M,"1,000,000+",Free,0,Everyone,Communication,"July 6, 2018",5.2,5.0 and up
10730,FP Notebook,MEDICAL,4.5,410,60M,"50,000+",Free,0,Everyone,Medical,"March 24, 2018",2.1.0.372,4.4 and up
10753,Slickdeals: Coupons & Shopping,SHOPPING,4.5,33599,12M,"1,000,000+",Free,0,Everyone,Shopping,"July 30, 2018",3.9,4.4 and up
10768,AAFP,MEDICAL,3.8,63,24M,"10,000+",Free,0,Everyone,Medical,"June 22, 2018",2.3.1,5.0 and up

In [12]:
total_duplicate = len(android[android.duplicated(['App'])])
total_duplicate

1181

In [13]:
android[android.App == 'Instagram'] ## Look for sepcific app and keep app which has higher reviews

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2545,Instagram,SOCIAL,4.5,66577313,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device
2604,Instagram,SOCIAL,4.5,66577446,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device
2611,Instagram,SOCIAL,4.5,66577313,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device
3909,Instagram,SOCIAL,4.5,66509917,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device

In [14]:
android_groupby = android.groupby(by='App')['Reviews'].max()
android_groupby['Instagram']

'66577446'

In [15]:
android_clean = pd.merge(android,android_groupby,how="inner",on=['App','Reviews'])
android_clean[android_clean.App == 'Quick PDF Scanner + OCR FREE'] ## Look for sepcific app

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
214,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,"5,000,000+",Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up
215,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,"5,000,000+",Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up

In [16]:
#After joining, still there is some duplicates record as see in above example.
android_clean.drop_duplicates(subset=['App','Reviews'],inplace=True)

In [17]:
android_clean[android_clean.App == 'Quick PDF Scanner + OCR FREE']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
214,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,"5,000,000+",Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up

In [18]:
print("Expected Length:",len(android)-total_duplicate)
print("Actula Legnth:",len(android_clean))

Expected Length: 9659
Actula Legnth: 9659

In [19]:
print(explore_data(android_clean))
android_clean.head(3)

Number of Rows:  9659
Number of Cols:  13

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
2,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up

## Filter Eng Apps

In [20]:
android_clean.iloc[7940][0]

'PHARMAGUIDE (DZ)'

In [21]:
def is_english(string):
    non_ascii = 0
    for char in string:
        if ord(char) > 127:
            non_ascii +=1
    
    if non_ascii > 3:
        return False
    else:
        return True
# print(is_english('Docs To Go™ Free Office Suite'))
# print(is_english('Instachat 😜'))

In [22]:
android_clean['isEng'] = android_clean.App.apply(is_english)
ios['isEng'] = ios.track_name.apply(is_english)

In [23]:
android_clean[android_clean.isEng == False].head(3) ## List down non-english Android app

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,isEng
608,Flame - درب عقلك يوميا,EDUCATION,4.6,56065,37M,"1,000,000+",Free,0,Everyone,Education,"July 26, 2018",3.3,4.1 and up,False
1376,သိင်္ Astrology - Min Thein Kha BayDin,LIFESTYLE,4.7,2225,15M,"100,000+",Free,0,Everyone,Lifestyle,"July 26, 2018",4.2.1,4.0.3 and up,False
3224,РИА Новости,NEWS_AND_MAGAZINES,4.5,44274,8.0M,"1,000,000+",Free,0,Everyone,News & Magazines,"August 6, 2018",4.0.6,4.4 and up,False

In [24]:
ios[ios.isEng == False].head(3) ## List down non-english ios app

,id,track_name,size_bytes,currency,price,rating_count_tot,rating_count_ver,user_rating,user_rating_ver,ver,cont_rating,prime_genre,sup_devices.num,ipadSc_urls.num,lang.num,vpp_lic,isEng
813,445375097,爱奇艺PPS -《欢乐颂2》电视剧热播,224617472,USD,0.0,14844,0,4.0,0.0,6.3.3,17+,Entertainment,38,5,3,1,False
1193,405667771,"聚力视频HD-人民的名义,跨界歌王全网热播",90725376,USD,0.0,7446,8,4.0,4.5,5.0.8,12+,Entertainment,24,4,1,1,False
1427,336141475,优酷视频,204959744,USD,0.0,4885,0,3.5,0.0,6.7.0,12+,Entertainment,38,0,2,1,False

In [25]:
android_eng = android_clean[android_clean.isEng == True]
ios_eng = ios[ios.isEng == True]

In [26]:
explore_data(android_eng)
android_eng.head(3)

Number of Rows:  9614
Number of Cols:  14

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,isEng
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,True
1,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,True
2,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,True

In [27]:
explore_data(ios_eng)
ios_eng.head(3)

Number of Rows:  6183
Number of Cols:  17

,id,track_name,size_bytes,currency,price,rating_count_tot,rating_count_ver,user_rating,user_rating_ver,ver,cont_rating,prime_genre,sup_devices.num,ipadSc_urls.num,lang.num,vpp_lic,isEng
0,284882215,Facebook,389879808,USD,0.0,2974676,212,3.5,3.5,95.0,4+,Social Networking,37,1,29,1,True
1,389801252,Instagram,113954816,USD,0.0,2161558,1289,4.5,4.0,10.23,12+,Photo & Video,37,0,29,1,True
2,529479190,Clash of Clans,116476928,USD,0.0,2130805,579,4.5,4.5,9.24.12,9+,Games,38,5,18,1,True

## Filter Free Apps

In [28]:
def isFreeApp(price):
    try:
        price = float(price)
    except:
        price = float(price[1:])
    if price == 0.0:
        return 0 # Free
    else:
        return 1 # Paid

In [68]:
android_eng['isFree'] = android_eng.Price.apply(isFreeApp)
android_free = android_eng[android_eng.isFree == 0] ## Free App

ios_eng['isFree'] = ios_eng.price.apply(isFreeApp)
ios_free = ios_eng[ios_eng.isFree == 0] ## Free App

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [69]:
explore_data(android_free)
android_free.head(3)

Number of Rows:  8862
Number of Cols:  15

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,isEng,isFree
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,True,0
1,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,True,0
2,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,True,0

In [31]:
explore_data(ios_free)
ios_free.head(3)

Number of Rows:  3222
Number of Cols:  18

,id,track_name,size_bytes,currency,price,rating_count_tot,rating_count_ver,user_rating,user_rating_ver,ver,cont_rating,prime_genre,sup_devices.num,ipadSc_urls.num,lang.num,vpp_lic,isEng,isFree
0,284882215,Facebook,389879808,USD,0.0,2974676,212,3.5,3.5,95.0,4+,Social Networking,37,1,29,1,True,0
1,389801252,Instagram,113954816,USD,0.0,2161558,1289,4.5,4.0,10.23,12+,Photo & Video,37,0,29,1,True,0
2,529479190,Clash of Clans,116476928,USD,0.0,2130805,579,4.5,4.5,9.24.12,9+,Games,38,5,18,1,True,0

## Most common apps by Genere

In [32]:
def freq_table(count_genere,length_data):
    return float( round((count_genere/length_data)*100 ,2 ))

In [33]:
def groupByCol(df,groupby,count_col):
    df_cat = df.groupby(by=groupby)[count_col].count()
    df_cat = pd.DataFrame(df_cat).reset_index()
    df_cat.columns = [groupby, 'col_count']
    
    df_cat['percentage'] = df_cat.col_count.apply(freq_table,length_data=len(df))
    df_cat.sort_values(by='percentage',ascending=False,inplace=True)
    
    return df_cat

### Android - List by Genere

In [34]:
android_genere = groupByCol(android_free,groupby="Genres",count_col="App")
android_genere.head(3)

            Genres  col_count  percentage
104          Tools        748        8.44
49   Entertainment        538        6.07
36       Education        474        5.35

### Android -  List by Category

In [35]:
android_genere = groupByCol(android_free,groupby="Category",count_col="App")
android_genere.head(3)

   Category  col_count  percentage
11   FAMILY       1678       18.93
14     GAME        859        9.69
29    TOOLS        749        8.45

In [36]:
## list by prime_genere
ios_genere = groupByCol(ios_free,groupby="prime_genre",count_col="track_name")
ios_genere.head(3)

      prime_genre  col_count  percentage
7           Games       1874       58.16
4   Entertainment        254        7.88
14  Photo & Video        160        4.97

## Avg user_Rating for ios

In [37]:
def ios_user_rating_table1(dataset,index):
    data_genere={}
    user_ratings={}
    
    for data in dataset:
        genere = data[index]
        if genere in user_ratings:
            user_ratings[genere] += float(data[5])
            data_genere[genere] += 1 
        else:
            user_ratings[genere] = float(data[5])
            data_genere[genere] = 1 
    
    freq = {}       
    for key,value in user_ratings.items():
        freq[key] = round(value/data_genere[key],2)
    return freq

#ios_user_rating_table1(ios_free,11)

In [38]:
ios_user_rating = ios_free.groupby(by="prime_genre")['rating_count_tot'].describe()
ios_user_rating = ios_user_rating.loc[:,['mean']]
ios_user_rating.sort_values(by='mean',ascending=False,inplace=True)

ios_user_rating

                           mean
prime_genre
Navigation         86090.333333
Reference          74942.111111
Social Networking  71548.349057
Music              57326.530303
Weather            52279.892857
Book               39758.500000
Food & Drink       33333.923077
Finance            31467.944444
Photo & Video      28441.543750
Travel             28243.800000
Shopping           26919.690476
Health & Fitness   23298.015385
Sports             23008.898551
Games              22788.669691
News               21248.023256
Productivity       21028.410714
Utilities          18684.456790
Lifestyle          16485.764706
Entertainment      14029.830709
Business            7491.117647
Education           7003.983051
Catalogs            4004.000000
Medical              612.000000

## Find installs for Android

In [70]:
android_free['Installs'] = android_free['Installs'].str.replace("+","")
android_free['Installs'] = pd.to_numeric(android_free['Installs'].str.replace(",",""))

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [71]:
android_free.head(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,isEng,isFree
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,True,0
1,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,True,0
2,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,50000000,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,True,0

In [91]:
android_user_installs = android_free.groupby(by="Category")['Installs'].describe()
android_user_installs = android_user_installs.loc[:,['mean']]
ios_user_rating.sort_values(by='mean',ascending=False,inplace=True)
android_user_installs.round(2)

                            mean
Category
ART_AND_DESIGN        1986335.09
AUTO_AND_VEHICLES      647317.82
BEAUTY                 513151.89
BOOKS_AND_REFERENCE   8767811.89
BUSINESS              1712290.15
COMICS                 817657.27
COMMUNICATION        38456119.17
DATING                 854028.83
EDUCATION             1820673.08
ENTERTAINMENT        11640705.88
EVENTS                 253542.22
FAMILY                3694276.33
FINANCE               1387692.48
FOOD_AND_DRINK        1924897.74
GAME                 15560965.60
HEALTH_AND_FITNESS    4188821.99
HOUSE_AND_HOME        1331540.56
LIBRARIES_AND_DEMO     638503.73
LIFESTYLE             1437816.27
MAPS_AND_NAVIGATION   4056941.77
MEDICAL                120616.49
NEWS_AND_MAGAZINES    9549178.47
PARENTING              542603.62
PERSONALIZATION       5201482.61
PHOTOGRAPHY          17805627.64
PRODUCTIVITY         16787331.34
SHOPPING              7036877.31
SOCIAL               23253652.13
SPORTS                3638640.14
TOOLS                10682301.03
TRAVEL_AND_LOCAL     13984077.71
VIDEO_PLAYERS        24727872.45
WEATHER               5074486.20